variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn package -B -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - master_new
    - recreate_db
docker-build:
  stage: package
  tags:
    - k8s
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_PIPELINE_IID
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_PROJECT_DIR
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --cache=true --destination $CI_REGISTRY_IMAGE:ci-$CI_PIPELINE_IID
  only:
    - master_new
    - recreate_db
      #server-deploy:
      #image: alpine:latest
      #stage: deploy
      #tags:
      #- deployment
      #script:
      #- echo $ID_RSA
      #- echo $SERVER_USER
      #- echo $SERVER_IP
      #- echo $CI_BUILD_TOKEN
      #- echo $CI_REGISTRY
      #- chmod og= $ID_RSA
      #- apk update && apk add openssh-client
      #- ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
      #- ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
      #- ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f data-management-backend || true"
      #- ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8080:8080 --name data-management-backend $TAG_COMMIT --env SPRING_DATASOURCE_URL=jdbc:mysql://root_mysql-standalone_1:3306/my_db"
      #environment:
      #name: production
      #url: http://134.122.86.52

