stages:
  - build

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mkdir /downloads
    - cd /builds/nomaten/DataManagementBackend
    - ls
  artifacts:
    paths:
      - /builds/nomaten/DataManagementBackend



#stages:
#  - publish
#
#variables:
#  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
#  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
#
#publish:
#  image: openjdk:8
#  stage: publish
#  services:
#    - docker:dind
#  script:
#    - sudo apt install docker.io
#    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#    - docker push $TAG_COMMIT
#    - docker push $TAG_LATEST

