version: '3'
services:
        mysql-standalone:
                image: 'mysql:8.0.23'
                environment:
                        - MYSQL_ROOT_PASSWORD=root_pass
                        - MYSQL_USER=mpecel
                        - MYSQL_PASSWORD=mpecel_pass
                        - MYSQL_DATABASE=my_db
                ports:
                        - "6666:3306"
                volumes:
                        - /home/my_mysql:/var/lib/mysql
        springboot-application:
                image: registry.gitlab.com/nomaten/datamanagementbackend/gitlab_pipeline:dcd4f3c2
                environment:
                        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/my_db
                ports:
                        - "8080:8080"
                volumes:
                        - /home/my_spring:/storage
                depends_on:
                        - mysql-standalone

